services:

  message-broker:
    image: dimaubuntu/message-broker:latest
    ports:
      - "8018:8080"
    depends_on:
      - redis-gateway
      - db_message_broker
      - discovery-service
      - communication-service
      - user-management-service
    environment:
      - SPRING_APPLICATION_NAME=message-broker
      - SERVER_PORT=8080
      - DISCOVERY_SERVICE_URL=http://discovery-service:8989
      - DISCOVERY_SERVICE_GRPC_URL=discovery-service:6565
      - MESSAGE_BROKER_POSTGRES_HOST=db_message_broker
      - MESSAGE_BROKER_POSTGRES_DB_PORT=5432
      - MESSAGE_BROKER_POSTGRES_USER=${MESSAGE_BROKER_POSTGRES_USER}
      - MESSAGE_BROKER_POSTGRES_PASSWORD=${MESSAGE_BROKER_POSTGRES_PASSWORD}
      - MESSAGE_BROKER_POSTGRES_DB=${MESSAGE_BROKER_POSTGRES_DB}
      - GATEWAY_SERVICE_URL=${GATEWAY_SERVICE_URL}
    networks:
      - app-network
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  db_message_broker:
    image: postgres:17
    environment:
      - POSTGRES_USER=${MESSAGE_BROKER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${MESSAGE_BROKER_POSTGRES_PASSWORD}
      - POSTGRES_DB=${MESSAGE_BROKER_POSTGRES_DB}
    volumes:
      - message_broker_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      replicas: 1

  gateway-service:
    image: dimaubuntu/gateway-service:latest
    ports:
      - "8088:8080"
    depends_on:
      - redis-gateway
      - communication-service
      - user-management-service
    environment:
      - SPRING_REDIS_HOST=redis-gateway
      - SPRING_REDIS_PORT=6379
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SERVICES_USER_URL=${SERVICES_USER_URL}
      - USER_MANAGEMENT_SERVICE_HOST=user-management-service
      - USER_MANAGEMENT_SERVICE_PORT=80
      - COMMUNICATION_SERVICE_HOST=communication-service
      - COMMUNICATION_SERVICE_PORT=8080
      - RUMOURS_SERVICE_HOST=rumours-service
      - RUMOURS_SERVICE_PORT=8080
      - CHARACTER_SERVICE_HOST=character-service
      - CHARACTER_SERVICE_PORT=8081
      - TOWN_SERVICE_HOST=town-service
      - TOWN_SERVICE_PORT=8080
      - GAME_SERVICE_HOST=game-service
      - GAME_SERVICE_PORT=80
      - GATEWAY_SERVICE_URL=http://gateway-service:8080
      - DISCOVERY_SERVICE_GRPC_URL=discovery-service:6565
      - TASK_SERVICE_HOST=task-service
      - TASK_SERVICE_PORT=8000
      - VOTING_SERVICE_HOST=voting-service
      - VOTING_SERVICE_PORT=8000
      - DISCOVERY_SERVICE_URL=${DISCOVERY_SERVICE_URL}
    networks:
      - app-network
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  redis-gateway:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --protected-mode no --appendonly yes
    volumes:
      - redis-gateway-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 2s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - app-network
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    restart: unless-stopped

  discovery-service:
    image: dimaubuntu/service-discovery:latest
    environment:
      - SERVER_PORT=8989
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - ALERT_EMAIL_TO=${ALERT_EMAIL_TO}
      - ALERT_EMAIL_FROM=${ALERT_EMAIL_FROM}
      - ALERTS_ENABLED=${ALERTS_ENABLED}
    ports:
      - "8989:8989" # REST
      - "6565:6565" # gRPC
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://discovery-service:8989/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  town-service:
    image: dimaubuntu/town-service:latest
    environment:
      - SPRING_APPLICATION_NAME=town-service
      - SERVER_PORT=8080
      - GRPC_PORT=6565
      - DISCOVERY_SERVICE_URL=http://discovery-service:8989
      - MESSAGE_BROKER_GRPC_URL=message-broker:6565
      - TOWN_SERVICE_POSTGRES_HOST=db_town_service
      - TOWN_SERVICE_POSTGRES_DB_PORT=5432
      - TOWN_SERVICE_POSTGRES_USER=${TOWN_SERVICE_POSTGRES_USER}
      - TOWN_SERVICE_POSTGRES_PASSWORD=${TOWN_SERVICE_POSTGRES_PASSWORD}
      - TOWN_SERVICE_POSTGRES_DB=${TOWN_SERVICE_POSTGRES_DB}
      - GATEWAY_SERVICE_URL=${GATEWAY_SERVICE_URL}
    networks:
      - app-network
    deploy:
      replicas: 2
      endpoint_mode: dnsrr

  character-service:
    image: dimaubuntu/character-service:latest
    environment:
      - SPRING_APPLICATION_NAME=character-service
      - SERVER_PORT=8081
      - DISCOVERY_SERVICE_URL=http://discovery-service:8989
      - DISCOVERY_SERVICE_GRPC_URL=discovery-service:6565
      - CHARACTER_SERVICE_POSTGRES_HOST=db_character_service
      - CHARACTER_SERVICE_POSTGRES_DB_PORT=5432
      - CHARACTER_SERVICE_POSTGRES_USER=${CHARACTER_SERVICE_POSTGRES_USER}
      - CHARACTER_SERVICE_POSTGRES_PASSWORD=${CHARACTER_SERVICE_POSTGRES_PASSWORD}
      - CHARACTER_SERVICE_POSTGRES_DB=${CHARACTER_SERVICE_POSTGRES_DB}
      - GATEWAY_SERVICE_URL=${GATEWAY_SERVICE_URL}
    networks:
      - app-network
    deploy:
      replicas: 2
      endpoint_mode: dnsrr

  db_town_service:
    image: postgres:17
    environment:
      - POSTGRES_USER=${TOWN_SERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TOWN_SERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TOWN_SERVICE_POSTGRES_DB}
    volumes:
      - town_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      replicas: 1

  db_character_service:
    image: postgres:17
    environment:
      - POSTGRES_USER=${CHARACTER_SERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${CHARACTER_SERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${CHARACTER_SERVICE_POSTGRES_DB}
    volumes:
      - character_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      replicas: 1

  task-service:
    image: dimaubuntu/task-service:latest
    pull_policy: always
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    environment:
      SERVICE_NAME: task-service
      SERVICE_PORT: 8000
      DISCOVERY_SERVICE_URL: discovery-service:6565
      POSTGRES_USER: ${TASK_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TASK_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TASK_SERVICE_POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    networks:
      - app-network
    deploy:
      replicas: 2
      endpoint_mode: dnsrr
    depends_on:
      discovery-service:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: task-service-db
    restart: always
    networks:
      - app-network
    environment:
      POSTGRES_USER: ${TASK_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TASK_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TASK_SERVICE_POSTGRES_DB}
    ports:
      - "5469:5432"
    volumes:
      - task_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${TASK_SERVICE_POSTGRES_USER} -d ${TASK_SERVICE_POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10

  voting-service:
    image: dimaubuntu/voting-service:latest
    working_dir: /app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    environment:
      SERVICE_NAME: voting-service
      SERVICE_PORT: 8000
      DISCOVERY_SERVICE_URL: discovery-service:6565
      VOTING_SERVICE_POSTGRES_USER: ${VOTING_SERVICE_POSTGRES_USER}
      VOTING_SERVICE_POSTGRES_PASSWORD: ${VOTING_SERVICE_POSTGRES_PASSWORD}
      VOTING_SERVICE_POSTGRES_DB: ${VOTING_SERVICE_POSTGRES_DB}
      VOTING_SERVICE_DB_HOST: db_voting_service
      VOTING_SERVICE_POSTGRES_PORT: 5432
    networks:
      - app-network
    deploy:
      replicas: 2
      endpoint_mode: dnsrr
    depends_on:
      db_voting_service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy

  db_voting_service:
    image: postgres:17
    environment:
      POSTGRES_USER: ${VOTING_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${VOTING_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${VOTING_SERVICE_POSTGRES_DB}
    ports:
      - "${VOTING_SERVICE_POSTGRES_PORT}:5432"
    networks:
      - app-network
    volumes:
      - voting_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${VOTING_SERVICE_POSTGRES_USER} -d ${VOTING_SERVICE_POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10

  db_rumours_service:
    image: postgres:17
    environment:
      POSTGRES_USER: ${RUMOURS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${RUMOURS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${RUMOURS_POSTGRES_DB}
    ports:
      - "${RUMOURS_POSTGRES_DB_PORT}:5432"
    volumes:
      - rumours_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${RUMOURS_POSTGRES_USER} -d ${RUMOURS_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rumours-service:
    image: m1rrerror/mafia-rumours-service:latest
    environment:
      DB_CONNECTION_STRING: "Host=db_rumours_service;Port=5432;Database=${RUMOURS_POSTGRES_DB};Username=${RUMOURS_POSTGRES_USER};Password=${RUMOURS_POSTGRES_PASSWORD}"
      GATEWAY_SERVICE_URL: ${GATEWAY_SERVICE_URL}
      DISCOVERY_SERVICE_URL: ${DISCOVERY_SERVICE_URL}
      SERVICE_HOST: rumours-service
      SERVICE_PORT: 8080
      RPC_PORT: 6000
      DISCOVERY_SERVICE_GRPC_URL: "http://discovery-service:6565"
      SERVICE_TOPIC: "rumours-topic"
      SUBSCRIBED_TOPICS: "user-management"
      SERVICE_ID: rumours-service
    depends_on:
      db_rumours_service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    networks:
      - app-network
    deploy:
      replicas: 2
      endpoint_mode: dnsrr

  db_communication_service:
    image: postgres:17
    environment:
      POSTGRES_USER: ${COMM_POSTGRES_USER}
      POSTGRES_PASSWORD: ${COMM_POSTGRES_PASSWORD}
      POSTGRES_DB: ${COMM_POSTGRES_DB}
    ports:
      - "${COMM_POSTGRES_DB_PORT}:5432"
    volumes:
      - communication_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${COMM_POSTGRES_USER} -d ${COMM_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  communication-service:
    image: m1rrerror/mafia-communication-service:latest
    environment:
      ConnectionStrings__DefaultConnection: "Host=db_communication_service;Port=5432;Database=${COMM_POSTGRES_DB};Username=${COMM_POSTGRES_USER};Password=${COMM_POSTGRES_PASSWORD}"
      DISCOVERY_SERVICE_URL: ${DISCOVERY_SERVICE_URL}
      SERVICE_HOST: communication-service
      SERVICE_PORT: 8080
      RPC_PORT: 6000
      DISCOVERY_SERVICE_GRPC_URL: "http://discovery-service:6565"
      SERVICE_TOPIC: "chat-topic"
      SUBSCRIBED_TOPICS: "chat-events"
      SERVICE_ID: communication-service
    depends_on:
      db_communication_service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    networks:
      - app-network
    deploy:
      replicas: 2
      endpoint_mode: dnsrr

  db_user_management_service:
    image: postgres:14
    environment:
      POSTGRES_USER: ${USER_MANAGEMENT_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_MANAGEMENT_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_MANAGEMENT_SERVICE_POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - user_management_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER_MANAGEMENT_SERVICE_POSTGRES_USER} -d ${USER_MANAGEMENT_SERVICE_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user-management-service:
    image: alexandrina581/user-management-service:latest
    pull_policy: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - "6567:6565"
    env_file:
      - .env
    environment:
      SERVICE_NAME: user-management-service
      HOSTNAME: user-management-service
      RPC_PORT: 6565
      TOPIC_NAME: user-management
      MESSAGE_BROKER_GRPC_URL: message-broker:6565
      DISCOVERY_SERVICE_GRPC_URL: discovery-service:6565
      SERVICE_PORT: 80
      USER_MANAGEMENT_SERVICE_POSTGRES_USER: ${USER_MANAGEMENT_SERVICE_POSTGRES_USER}
      USER_MANAGEMENT_SERVICE_POSTGRES_PASSWORD: ${USER_MANAGEMENT_SERVICE_POSTGRES_PASSWORD}
      USER_MANAGEMENT_SERVICE_POSTGRES_DB: ${USER_MANAGEMENT_SERVICE_POSTGRES_DB}
      USER_MANAGEMENT_SERVICE_POSTGRES_HOST: db_user_management_service
      USER_MANAGEMENT_SERVICE_POSTGRES_PORT: 5432
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
    depends_on:
      db_user_management_service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    networks:
      - app-network
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    labels:
      logging: "promtail"
      logging_jobname: "user-management-service"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - app-network
    depends_on:
      discovery-service:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    networks:
      - app-network

  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - app-network


networks:
  app-network:
    driver: overlay
    attachable: true

volumes:
  town_postgres_data:
  message_broker_postgres_data:
  character_postgres_data:
  communication_postgres_data:
  rumours_postgres_data:
  shop_postgres_data:
  roleplay_postgres_data:
  prometheus_data:
  grafana_data:
  loki_data:
  redis-gateway-data:
  task_pgdata:
  voting_postgres_data:
  user_management_postgres_data:
  game_postgres_data:
